Updating deps and fixing the annoying warning message “Emphasis must use * as marker”
funbox/markdown-lint pull request #1
Opened 2020-12-02 22:05 UTC by 343dev

2020-12-03 10:15 UTC, igoradamenko approved these changes
LGTM.

@dissimulazione, do you mind to check?

2020-12-07 21:06 UTC, dissimulazione requested changes

2020-12-07 21:06 UTC, dissimulazione commented on MIGRATION.md
> +If you are using a custom configuration file, then you should check the
I'm not sure, but that line seems weird, maybe it's just Present Simple here, not Continuous?

And I think there's no need in "the" articles here either.

2020-12-07 21:06 UTC, dissimulazione commented on MIGRATION.md
> +unexpected behavior.
An unexpected?

2020-12-07 21:06 UTC, dissimulazione commented on CHANGELOG.md
> +- Updated [.markdownlintrc.js](.markdownlintrc.js) to match the new versions.
Maybe there's no need in "the" article here?

2020-12-09 10:54 UTC, dissimulazione approved these changes

2020-12-09 15:19 UTC, igoradamenko commented
Published @funboxteam/markdown-lint@2.0.0.

2020-12-09 15:19 UTC, merged